### ISSUE TITLE
Compatibility with Python 3.5 ?

### ISSUE THREAD

**Issue by stdex** [cr0hn/ktcal2#2]
Task exception was never retrieved
future: <Task finished coro=<_check_credentials() done, defined at /usr/local/lib/python3.5/dist-packages/ktcal2/lib/ssh_brute.py:50> exception=TypeError("create_connection() got an unexpected keyword argument 'server_host_keys'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/ktcal2/lib/ssh_brute.py", line 93, in _check_credentials
    server_host_keys=None)
TypeError: create_connection() got an unexpected keyword argument 'server_host_keys'

**Comment by isgroup-srl** [comment]
Same issue here +1
